# This file is part of the OpenMiamMiam project.
#
# (c) Isics <contact@isics.fr>
#
# This source file is subject to the AGPL v3 license that is bundled
# with this source code in the file LICENSE.

#
# General
#
open_miam_miam.admin:
    pattern:  /
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\General:index }



#
# Super admin
#
open_miam_miam.admin.super.show_dashboard:
    pattern:  /super/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\General:showDashboard }

open_miam_miam.admin.super.user_switch.list:
    pattern:  /super/user-switch
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\UserSwitch:list }

open_miam_miam.admin.super.article.list:
    pattern:  /super/articles
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Article:list }

open_miam_miam.admin.super.article.create:
    pattern:  /super/articles/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Article:create }

open_miam_miam.admin.super.article.edit:
    pattern:  /super/articles/{articleId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Article:edit }

open_miam_miam.admin.super.article.delete:
    pattern:  /super/articles/{articleId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Article:delete }

open_miam_miam.admin.super.newsletter.create:
    pattern:  /super/newsletters
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Newsletter:create }

open_miam_miam.admin.super.newsletter.edit:
    pattern:  /super/newsletters/{newsletterId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Newsletter:edit }

open_miam_miam.admin.super.newsletter.send:
    pattern:  /super/newsletters/{newsletterId}/send
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Newsletter:send }

open_miam_miam.admin.super.newsletter.report:
    pattern:  /super/newsletters/{newsletterId}/report
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Super\Newsletter:showReport }

#
# Admin Association
#
open_miam_miam.admin.association.show_dashboard:
    pattern:  /associations/{id}/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\General:showDashboard }

open_miam_miam.admin.association.sales_order.list:
    pattern:  /associations/{id}/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:list }

open_miam_miam.admin.association.sales_order.list_for_branch_occurrence:
    pattern:  /associations/{id}/sales_orders/branch_occurrences/{branchOccurrenceId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:listForBranchOccurrence }

open_miam_miam.admin.association.sales_orders.get_sales_orders_pdf_for_branch_occurrence:
    pattern:  /associations/{id}/sales_orders/branch_occurrences/{branchOccurrenceId}/pdfs/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:getSalesOrdersPdfForBranchOccurrence }

open_miam_miam.admin.association.sales_order.view:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:view }

open_miam_miam.admin.association.sales_order.edit:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/edit
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:edit }

open_miam_miam.admin.association.sales_order.delete_row:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/rows/{salesOrderRowId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:deleteSalesOrderRow }

open_miam_miam.admin.association.sales_order.add_products:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/add_products
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:addProducts }

open_miam_miam.admin.association.sales_order.add_product:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/add_product/{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:addProduct }

open_miam_miam.admin.association.sales_order.add_artificial_product:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/rows/add/{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:addSalesOrderRow }

open_miam_miam.admin.association.sales_order.pay:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/pay
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:Pay }

open_miam_miam.admin.association.sales_order.delete_payment_allocation:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/payments/allocations/{paymentAllocationId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:deletePaymentAllocation }

open_miam_miam.admin.association.sales_order.allocate_payment:
    pattern:  /associations/{id}/sales_orders/{salesOrderId}/payments/{paymentId}/allocate
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\SalesOrder:allocatePayment }

open_miam_miam.admin.association.branch.list:
    pattern:  /associations/{id}/branches
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Branch:list }

open_miam_miam.admin.association.branch.create:
    pattern:  /associations/{id}/branches/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Branch:create }

open_miam_miam.admin.association.branch.edit:
    pattern:  /associations/{id}/branches/{branchId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Branch:edit }

open_miam_miam.admin.association.branch.edit_calendar:
    pattern:  /associations/{id}/branches/{branchId}/calendar
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Branch:editCalendar }

open_miam_miam.admin.association.branch.delete_occurrence:
    pattern:  /associations/{id}/branches/{branchId}/calendar/{branchOccurrenceId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Branch:deleteOccurrence }

open_miam_miam.admin.association.branch.delete:
    pattern:  /associations/{id}/branches/{branchId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Branch:delete }

open_miam_miam.admin.association.consumer.list:
    pattern:  /associations/{id}/consumers
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:list }

open_miam_miam.admin.association.consumer.list_payments:
    pattern:  /associations/{id}/consumers/{consumerId}/payments
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:listPayments }

open_miam_miam.admin.association.consumer.create_payment:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:createPayment }

open_miam_miam.admin.association.consumer.edit_payment:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/{paymentId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:editPayment }

open_miam_miam.admin.association.consumer.delete_payment:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/{paymentId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:deletePayment }

open_miam_miam.admin.association.consumer.delete_payment_allocation:
    pattern: /associations/{id}/consumers/{consumerId}/payments/allocations/{paymentAllocationId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:deletePaymentAllocation }

open_miam_miam.admin.association.consumer.allocate_sales_order:
    pattern:  /associations/{id}/consumers/{consumerId}/payments/{paymentId}/allocate_sales_order/{salesOrderId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Consumer:allocateSalesOrder }

open_miam_miam.admin.association.article.list:
    pattern:  /associations/{id}/articles
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Article:list }

open_miam_miam.admin.association.article.create:
    pattern:  /associations/{id}/articles/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Article:create }

open_miam_miam.admin.association.article.edit:
    pattern:  /associations/{id}/articles/{articleId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Article:edit }

open_miam_miam.admin.association.article.delete:
    pattern:  /associations/{id}/articles/{articleId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Article:delete }

open_miam_miam.admin.association.newsletter.create:
    pattern:  /associations/{id}/newsletters
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Newsletter:create }

open_miam_miam.admin.association.newsletter.edit:
    pattern:  /associations/{id}/newsletters/{newsletterId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Newsletter:edit }

open_miam_miam.admin.association.newsletter.send:
    pattern:  /associations/{id}/newsletters/{newsletterId}/send
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Newsletter:send }

open_miam_miam.admin.association.newsletter.report:
    pattern:  /associations/{id}/newsletters/{newsletterId}/report
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Association\Newsletter:showReport }

#
# Admin Producer
#
open_miam_miam.admin.producer.show_dashboard:
    pattern:  /producers/{id}/dashboard
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\General:showDashboard }

open_miam_miam.admin.producer.edit:
    pattern:  /producers/{id}/edit
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\General:edit }

open_miam_miam.admin.producer.product.list:
    pattern:  /producers/{id}/products
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:list }

open_miam_miam.admin.producer.product.create:
    pattern:  /producers/{id}/products/new
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:create }

open_miam_miam.admin.producer.product.edit:
    pattern:  /producers/{id}/products/{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:edit }

open_miam_miam.admin.producer.product.delete:
    pattern:  /producers/{id}/products/{productId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Product:delete }

open_miam_miam.admin.producer.calendar.edit:
    pattern:  /producers/{id}/calendar
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\Calendar:edit }

open_miam_miam.admin.producer.sales_order.list:
    pattern:  /producers/{id}/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:list }

open_miam_miam.admin.producer.sales_order.get_products_to_prepare_pdf_for_branch_occurrence:
    pattern:  /producers/{id}/sales_orders/branch_occurrences/{branchOccurrenceId}/pdfs/products_to_prepare
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:getProductsToPreparePdfForBranchOccurrence }

open_miam_miam.admin.producer.sales_order.get_sales_orders_pdf_for_branch_occurrence:
    pattern:  /producers/{id}/sales_orders/branch_occurrences/{branchOccurrenceId}/pdfs/sales_orders
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:getSalesOrdersPdfForBranchOccurrence }

open_miam_miam.admin.producer.sales_order.view:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:view }

open_miam_miam.admin.producer.sales_order.edit:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/edit
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:edit }

open_miam_miam.admin.producer.sales_order.delete_row:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/rows/{salesOrderRowId}/delete
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:deleteSalesOrderRow }

open_miam_miam.admin.producer.sales_order.add_products:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/add_products
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:addProducts }

open_miam_miam.admin.producer.sales_order.add_product:
    pattern:  /producers/{id}/sales_orders/{salesOrderId}/add_product/{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Admin\Producer\SalesOrder:addProduct }


