# This file is part of the OpenMiamMiam project.
#
# (c) Isics <contact@isics.fr>
#
# This source file is subject to the AGPL v3 license that is bundled
# with this source code in the file LICENSE.

#
# General
#
open_miam_miam.homepage:
    pattern:  /
    defaults: { _controller: IsicsOpenMiamMiamBundle:General:showHomepage }

open_miam_miam.article.list:
    pattern:  /news
    defaults: { _controller: IsicsOpenMiamMiamBundle:General:listArticles }

open_miam_miam.article.show:
    pattern:  /news/{articleSlug}-{articleId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:General:showArticle }
    requirements:
        articleSlug: '[^/]+'
        articleId:   '\d+'

open_miam_miam.association:
    pattern:  /association/{associationSlug}
    defaults: { _controller: IsicsOpenMiamMiamBundle:General:showAssociation }

open_miam_miam.producer:
    pattern:  /producer/{producerSlug}
    defaults: { _controller: IsicsOpenMiamMiamBundle:General:showProducer }

#
# Branch
#
open_miam_miam.branch.homepage:
    pattern:  /{branchSlug}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Branch:showHomepage }

open_miam_miam.branch.presentation:
    pattern:  /{branchSlug}/presentation
    defaults: { _controller: IsicsOpenMiamMiamBundle:Branch:showPresentation }

open_miam_miam.branch.article.list:
    pattern:  /{branchSlug}/news
    defaults: { _controller: IsicsOpenMiamMiamBundle:Branch:listArticles }

open_miam_miam.branch.article.show:
    pattern:  /{branchSlug}/news/{articleSlug}-{articleId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Branch:showArticle }
    requirements:
        articleSlug: '[^/]+'
        articleId:   '\d+'

open_miam_miam.branch.producers:
    pattern:  /{branchSlug}/producers
    defaults: { _controller: IsicsOpenMiamMiamBundle:Branch:listProducers }

#
# Cart
#
open_miam_miam.cart.show:
    pattern:  /{branchSlug}/cart
    defaults: { _controller: IsicsOpenMiamMiamBundle:Cart:show }
    requirements:
        _method: GET

open_miam_miam.cart.add:
    pattern:  /{branchSlug}/cart
    defaults: { _controller: IsicsOpenMiamMiamBundle:Cart:add }
    requirements:
        _method: POST

open_miam_miam.cart.update:
    pattern:  /{branchSlug}/cart
    defaults: { _controller: IsicsOpenMiamMiamBundle:Cart:update }
    requirements:
        _method: PUT

#
# Order
#
open_miam_miam.sales_order.confirm:
    pattern:  /{branchSlug}/order/confirm
    defaults: { _controller: IsicsOpenMiamMiamBundle:SalesOrder:Confirm }

open_miam_miam.sales_order.confirm_creation:
    pattern:  /{branchSlug}/order/{id}
    defaults: { _controller: IsicsOpenMiamMiamBundle:SalesOrder:ConfirmCreation }

#
# Catalog
#
open_miam_miam.catalog.product:
    pattern:  /{branchSlug}/{productSlug}-{productId}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Catalog:showProduct }
    requirements:
        productSlug: '[^/]+'
        productId:   '\d+'

open_miam_miam.catalog.category:
    pattern:  /{branchSlug}/{categorySlug}
    defaults: { _controller: IsicsOpenMiamMiamBundle:Catalog:showCategory }