Isics\Bundle\OpenMiamMiamBundle\Entity\Branch:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [name]
    properties:
        name:
            - NotNull: ~
            - Length:
                max: 128
        address1:
            - Length:
                max: 64
        address2:
            - Length:
                max: 64
        zipcode:
            - Length:
                max: 8
        city:
            - Length:
                max:  64
        phone1:
            - Length:
                max: 16
        phone2:
            - Length:
                max: 16
        website:
            - Url: ~
        facebook:
            - Url: ~