Isics\Bundle\OpenMiamMiamBundle\Model\Cart\Cart:
    properties:
        items:
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Model\Cart\CartItem:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\CartItem: ~
    properties:
        product:
            - NotNull: ~
        quantity:
            - GreaterThanOrEqual:
                value: 1
