Isics\Bundle\OpenMiamMiamBundle\Entity\Payment:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\Payment: ~
    properties:
        amount:
            - NotNull: ~
            - GreaterThan:
                value: 0
        rest:
            - NotNull: ~
        date:
            - NotNull: ~
            - Date: ~
        type:
            - Choice: { callback: getTypes }
        user:
            - Valid: ~
        association:
            - NotNull: ~
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Entity\PaymentAllocation:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\PaymentAllocation: ~
    properties:
        amount:
            - NotNull: ~
            - GreaterThan:
                value: 0
        date:
            - NotNull: ~
            - Date: ~
        salesOrder:
            - NotNull: ~
            - Valid: ~
        payment:
            - NotNull: ~
            - Valid: ~
