Isics\Bundle\OpenMiamMiamBundle\Model\SalesOrder\SalesOrderConfirmation:
    properties:
        termsOfSaleChecked:
            - "True": ~

Isics\Bundle\OpenMiamMiamBundle\Entity\SalesOrder:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\SalesOrder: ~
    properties:
        branchOccurrence:
            - NotNull: ~
            - Valid: ~
        salesOrderRows:
            - Valid: ~
        ref:
            - NotNull: ~
            - Length:
                max: 16
        date:
            - NotNull: ~
            - Date: ~
        total:
            - NotNull: ~
            - Type:
                type: numeric
        user:
            - Valid: ~
        firstname:
            - Length:
                max: 128
        lastname:
            - Length:
                max: 128
        address1:
            - Length:
                max: 64
        address2:
            - Length:
                max: 64
        zipcode:
            - Length:
                max: 8
        city:
            - Length:
                max: 64
        consumerComment:
            - Length:
                max: 255

Isics\Bundle\OpenMiamMiamBundle\Model\SalesOrder\ProducerSalesOrder:
    properties:
        salesOrderRows:
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Entity\SalesOrderRow:
    constraints:
            - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\SalesOrderRow: ~
    properties:
        product:
            - Valid: ~
        producer:
            - Valid: ~
        name:
            - NotNull: ~
            - Length:
                max: 128
        ref:
            - NotNull: ~
            - Length:
                max: 16
        isBio:
            - Type:
                type: boolean
        unitPrice:
            - GreaterThan:
                value: 0
        quantity:
            - NotNull: ~
            - GreaterThan:
                value: 0
        total:
            - NotNull: ~
            - GreaterThan:
                value: 0
