parameters:
    open_miam_miam_user.manager.user.class:            'Isics\Bundle\OpenMiamMiamUserBundle\Manager\UserManager'

services:
    open_miam_miam.form.type.user_registration:
        class: Isics\Bundle\OpenMiamMiamUserBundle\Form\Type\RegistrationType
        arguments:
            - %fos_user.model.user.class%
            - @open_miam_miam.twig.terms_of_service_extension
        tags:
            - { name: form.type, alias: open_miam_miam_user_registration }

    open_miam_miam.form.type.user_profile:
        class: Isics\Bundle\OpenMiamMiamUserBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: open_miam_miam_user_profile }

    open_miam_miam_user.listener.profile_editing:
        class: Isics\Bundle\OpenMiamMiamUserBundle\EventListener\ProfileEditingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    open_miam_miam_user.listener.authentication:
        class: Isics\Bundle\OpenMiamMiamUserBundle\EventListener\AuthenticationListener
        arguments:
            - @session
        tags:
            - { name: kernel.event_subscriber }

    open_miam_miam_user.manager.user:
        class: %open_miam_miam_user.manager.user.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %open_miam_miam_user.last_order_nb_days_considering_customer%
            - @security.acl.provider

    # Repositories
    open_miam_miam.repository.user:
        class: Isics\Bundle\OpenMiamMiamUserBundle\Entity\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  "getRepository"
        arguments:
            - "IsicsOpenMiamMiamUserBundle:User"

    # Twig extensions
    open_miam_miam.twig.open_miam_miam_user_extension:
        class:     Isics\Bundle\OpenMiamMiamUserBundle\Twig\OpenMiamMiamUserExtension
        arguments:
            - @open_miam_miam_user.manager.user
        tags:
            - { name: twig.extension }
